
#theme = "onedark"
theme = "catppuccin_frappe"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

###################################
### KEYS MAPPING
[keys.normal]
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file

### Go
[keys.normal.G]
p = ":insert-output echo -n 'println(\"\")'"

### Java
[keys.normal.J]
"l" = { "w" = [":insert-output echo -n 'LOG.warn();'"] }
"p" = ":insert-output echo -n 'System.out.println(\"\");'"
"m" = { "m" = ":insert-output echo -n 'public static void main(String[] args) {};'"}

### TS
[keys.normal.T]
"p" = ":insert-output echo -n 'console.log(\"\");'"

### Python
[keys.normal.P]
#"p" = ["insert_mode", "TEST!"]
"`" = { p = ["normal_mode", ":pipe echo '```python'", "collapse_selection", "insert_mode"] }
